source "https://rubygems.org"

gem "jekyll", "~> 3.10.0"
gem "jekyll-paginate", "~> 1.1"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-feed", "~> 0.17"
gem "kramdown", "~> 2.4.0"
gem "kramdown-parser-gfm", "~> 1.1"
gem "webrick", "~> 1.8"
